version: '3'
services:
  service-database:
    image: postgres:13.3
    restart: on-failure
    env_file:
      - .env
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"

  service:
    image: ivan-nosar/billing-service
    depends_on:
      - service-database
    links:
      - service-database
    restart: on-failure
    env_file:
      - .env
    ports:
      - "$HTTP_PORT:$HTTP_PORT"
    entrypoint: npm run start:service

  scheduler-database:
    image: mongo:5.0.1
    restart: on-failure
    env_file:
      - .env
    ports:
      - "$MONGO_PORT:$MONGO_PORT"

  scheduler:
    image: ivan-nosar/billing-service
    depends_on:
      - scheduler-database
    links:
      - scheduler-database
    restart: on-failure
    env_file:
      - .env
    entrypoint: npm run start:scheduler

  scheduler-executor:
    image: ivan-nosar/billing-service
    depends_on:
      - scheduler-database
    links:
      - scheduler-database
    restart: on-failure
    env_file:
      - .env
    entrypoint: npm run start:scheduler-executor

  nats:
    image: nats:latest
    restart: on-failure
    env_file:
      - .env
    ports:
      - "$NATS_MONITOR_PORT:$NATS_MONITOR_PORT"
      - "$NATS_ROUTE_PORT:$NATS_ROUTE_PORT"
      - "$NATS_CLIENT_PORT:$NATS_CLIENT_PORT"
